name: genrate ascii

on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps: 
        - name: check repo
          uses: actions/checkout@v4
        - name: install cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay CMD
          run: cowsay -f dragon " run for cover,Iam a ddddd dragon" >> dragan.txt
        - name: Test file exists
          run: grep -i "dragon" dragan.txt
        - name: Read file
          run: cat dragan.txt
        - name: checkout files
          run: ls -ltra

       # - name: List files
       #   run: ls
       # - name: read file
       #   run: cat README.md