name: genrate ascii

on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps: 
        - name: check repo
          uses: actions/checkout@v4
        - name: list files
          run: ls -ltra
        - name: Execute script
          run: ./ascii-script.sh
       

       # - name: List files
       #   run: ls
       # - name: read file
       #   run: cat README.md